# Generated by Django 4.1 on 2022-08-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome do paciente')),
                ('cpf', models.CharField(max_length=250, verbose_name='CPF ')),
                ('tipo_consulta', models.IntegerField(choices=[(1, 'Urgência'), (2, 'Avaliação'), (3, 'Paciente em tratamento'), (4, 'Retorno'), (5, 'Parceria')], verbose_name='Tipo de Consulta')),
                ('email', models.CharField(blank=True, max_length=250, null=True, verbose_name='E-mail')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('celular', models.CharField(max_length=250, verbose_name='Núm. celular')),
                ('pagamento', models.IntegerField(choices=[(1, 'Particular'), (2, 'Plano de Saúde'), (3, 'Parceria')], verbose_name='Pagamento')),
                ('especialidade', models.IntegerField(choices=[(1, 'Cirurgia'), (2, 'Endodontia'), (3, 'Ortodontia'), (4, 'HOF'), (5, 'Protese'), (6, 'Implantodontia')], verbose_name='Especialidade')),
                ('data_consulta', models.DateField(verbose_name='Data consulta')),
                ('hora_consulta', models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)], verbose_name='Horário consulta')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas agendadas',
            },
        ),
    ]
