# Generated by Django 4.1 on 2022-08-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF '),
        ),
    ]
