# Generated by Django 4.1 on 2022-08-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_agendamento_atualizado_em_alter_agendamento_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
