# Generated by Django 4.1 on 2022-08-26 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_alter_agendamento_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='agendamento',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='agendamentos.paciente'),
            preserve_default=False,
        ),
    ]
