# Generated by Django 4.1 on 2022-08-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0006_remove_agendamento_celular_remove_agendamento_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
