# Generated by Django 4.1 on 2022-09-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_paciente_atualizado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='arquivo',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(help_text='Digite somente os números.', max_length=250, verbose_name='Núm. celular'),
        ),
    ]
